/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/t3Hp3bMmVq0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function GiveawayPage() {
  return (<>
    <main
      className="flex flex-col items-center justify-center min-h-[100dvh] bg-gray-100 dark:bg-gray-900 p-4">
      <div className="max-w-md w-full space-y-6">
        <div className="text-center space-y-2">
          <h1 className="text-3xl font-bold">Join Our Giveaway</h1>
          <p className="text-gray-500 dark:text-gray-400">
            Enter your name and email to participate. Contract URL:
            <a className="text-blue-500 underline" href="#">
              https://example.com/giveaway-contract
            </a>
          </p>
        </div>
        <form className="space-y-4">
          <div>
            <Label htmlFor="name">Name</Label>
            <Input id="name" placeholder="Enter your name" required />
          </div>
          <div>
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="Enter your email" required type="email" />
          </div>
          <div />
          <Button className="w-full" type="submit">
            Join Giveaway
          </Button>
        </form>
        <div className="bg-white dark:bg-gray-800 rounded-md p-4 space-y-2">
          <h2 className="text-lg font-medium">Participants</h2>
          <ul className="space-y-1 text-sm">
            <li>example@email.com</li>
            <li>another@example.com</li>
            <li>participant@giveaway.com</li>
            <li>winner@contest.org</li>
            <li>lucky@draw.net</li>
          </ul>
        </div>
      </div>
    </main>
    <footer
      className="bg-gray-100 dark:bg-gray-900 text-center py-4 text-sm text-gray-500 dark:text-gray-400">
      Created by Bilkent Blockchain Society
    </footer>
  </>);
}
